const mainCard = [
  {
    id: 1,
    img: require("../../assets/images/momImage.png"),
    title: "جلسة نطق وتخاطب خاصة للطفل",
    date: "28 / 11 / 2020",
    time: "3 : 50 pm",
    location: "الرياض - شارع الملك عبد العزيز",
    logo: require("../../assets/images/lightLogo.png"),
  },
  {
    id: 2,
    img: require("../../assets/images/momImage.png"),
    title: "جلسة نطق وتخاطب خاصة للطفل",
    date: "28 / 11 / 2020",
    time: "3 : 50 pm",
    location: "الرياض - شارع الملك عبد العزيز",
    logo: require("../../assets/images/lightLogo.png"),
  },
  {
    id: 3,
    img: require("../../assets/images/momImage.png"),
    title: "جلسة نطق وتخاطب خاصة للطفل",
    date: "28 / 11 / 2020",
    time: "3 : 50 pm",
    location: "الرياض - شارع الملك عبد العزيز",
    logo: require("../../assets/images/lightLogo.png"),
  },
  {
    id: 4,
    img: require("../../assets/images/momImage.png"),
    title: "جلسة نطق وتخاطب خاصة للطفل",
    date: "28 / 11 / 2020",
    time: "3 : 50 pm",
    location: "الرياض - شارع الملك عبد العزيز",
    logo: require("../../assets/images/lightLogo.png"),
  },
  {
    id: 5,
    img: require("../../assets/images/momImage.png"),
    title: "جلسة نطق وتخاطب خاصة للطفل",
    date: "28 / 11 / 2020",
    time: "3 : 50 pm",
    location: "الرياض - شارع الملك عبد العزيز",
    logo: require("../../assets/images/lightLogo.png"),
  },
  {
    id: 6,
    img: require("../../assets/images/momImage.png"),
    title: "جلسة نطق وتخاطب خاصة للطفل",
    date: "28 / 11 / 2020",
    time: "3 : 50 pm",
    location: "الرياض - شارع الملك عبد العزيز",
    logo: require("../../assets/images/lightLogo.png"),
  },
];
export default mainCard;
